### ISSUE TITLE
Potential Null Pointer Dereference

### ISSUE THREAD

**Issue by sparticvs** [jeremycw/httpserver.h#19]
Used throughout, `realloc` may return a `null` pointer if there is a failure during allocation. The return value from realloc is never validated prior to use may lead to a null pointer dereference or information disclosure where an attacker may be able to leak information from memory.

**Comment by jeremycw** [comment]
Thanks, same with malloc too. I suppose I can sprinkle `assert(ptr != NULL);` after allocations

**Comment by jeremycw** [comment]
#20
