### ISSUE TITLE
how to use in c++11 project?

### ISSUE THREAD

**Issue by 96chh** [jeremycw/httpserver.h#41]
I use gcc version 4.8.5 with compile flag `-W -Wall -Wfatal-errors -g -std=c99 -std=c++11`, build error:

```
./deps/httpserver.h/jeremycw/httpserver.h: In function ‘void hs_init_session(http_request_t*)’:
./deps/httpserver.h/jeremycw/httpserver.h:1047:35: error: expected primary-expression before ‘)’ token
   session->parser = (http_parser_t){ };
                                   ^
compilation terminated due to -Wfatal-errors. 
```

**Comment by FightingBoom** [comment]
How do you solve this problem? thank you

**Comment by FightingBoom** [comment]
I used make clean, but this problem occurred again
`error: unknown type name 'clockid_t'
 extern int timerfd_create (clockid_t __clock_id, int __flags) __THROW;
                            ^`
