### ISSUE TITLE
Behaviour will be undefined when content length overflows an int

### ISSUE THREAD

**Issue by jeremycw** [jeremycw/httpserver.h#6]
Currently I just use an int to store the content length this will overflow for request bodies that are multiple gigabytes in size causing undefined behaviour. I need to protect against this in the request and response. I'll need to look into how to best handle this. I think I can probably just reject requests with a content length over some max value.

**Comment by jeremycw** [comment]
Looks like other servers max out at 2GB as well so I just need to handle it gracefully.

**Comment by Chess13234** [comment]
Why? many files are above 4GB. 
Just use uint64_t

**Comment by jeremycw** [comment]
Fixed
